name: CI
on:
  workflow_call:
    inputs:
      plugin:
        description: "Plugin name"
        type: string
        required: true
      repo:
        description: "Repo Short Url"
        type: string
        required: true
      tests:
        description: "Run tests"
        type: boolean
        required: false
        default: true
      docs:
        description: "Generate docs"
        type: boolean
        required: false
        default: true
      build:
        description: "Build"
        type: boolean
        required: false
        default: false
      release:
        description: "Release"
        type: boolean
        required: false
        default: true

jobs:
  stylua:
    name: Stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua

  debug:
    name: Check that no debug messages are left
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: folke/github/neovim@main
      - name: Check Debug
        run: /bin/grep --line-number -r '\\bdd(' lua || echo "No debug messages found"

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ inputs.tests }}
    steps:
      - uses: actions/checkout@v4
      - uses: folke/github/neovim@main
      - name: Test Cache
        uses: actions/cache@v4
        with:
          path: .tests
          key: ${{ runner.os }}-tests-${{ hashFiles('tests/minit.lua') }}
      - name: Run Tests
        run: ./scripts/test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: tests
    if: ${{ inputs.build }}
    steps:
      - uses: actions/checkout@v4
      - uses: folke/github/neovim@main
      - name: Run Build
        run: ./scripts/build
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(build): auto-generated build files"

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [tests, build]
    if: ${{ !failure() && inputs.docs && inputs.repo == github.repository && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: folke/github/neovim@main
      - name: Generate docs
        shell: bash
        run: |
          [ ! -f scripts/docs ] && exit 0
          ./scripts/docs
      - name: Create /doc
        run: mkdir -p doc
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ inputs.plugin }}
          version: "Neovim"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(build): auto-generate docs"

  release:
    name: release
    needs: tests
    if: ${{ inputs.release && inputs.repo == github.repository && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: release-please config
        id: release-please-config
        run: |
          if [ -f .github/release-please-config.json ]; then
            echo "config-file=.github/release-please-config.json" >> $GITHUB_OUTPUT
            [ -f .github/release-please-manifest.json ] &&
              echo "manifest-file=.github/release-please-manifest.json" >> $GITHUB_OUTPUT
            [ -f .github/.release-please-manifest.json ] &&
              echo "manifest-file=.github/.release-please-manifest.json" >> $GITHUB_OUTPUT
          else
            echo "release-type=simple" >> $GITHUB_OUTPUT
          fi
          exit 0
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: ${{ steps.release-please-config.outputs.config-file }}
          release-type: ${{ steps.release-please-config.outputs.release-type }}
          manifest-file: ${{ steps.release-please-config.outputs.manifest-file }}
      - name: tag stable versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable
