name: Example

on:
  push:
    branches: [main, master]
  pull_request:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review

permissions:
  pull-requests: read

jobs:
  ci:
    uses: folke/github/.github/workflows/ci.yml@main
    if: ${{ github.event_name != 'pull_request_target' }}
    secrets: inherit
    with:
      plugin: fooba
      
  pr-title:
    uses: folke/github/.github/workflows/pr.yml@main
    if: ${{ github.event_name == 'pull_request_target' }}
    secrets: inherit